[package]
name = "squalr-engine-debuggers"
version = "4.0.0"
authors = ["Zachary Canann"]
edition = "2024"
# build = "build.rs"

[dependencies]
squalr-engine-api = { path = "../squalr-engine-api" }

[build-dependencies]

